### ISSUE TITLE
Reporte de Práctica - Seguimiento y Control S4GPS

### ISSUE THREAD

**Issue by Yabin-2021** [SistemasTecTlaxiaco/actividad-9-practica-de-seguimiento-y-control-de-proyecto-entrevista-sistemhuerto#1]
Aquí se anexan los reportes de práctica.

**Comment by Yabin-2021** [comment]
Rúbrica
[Rúbrica reporte de practica de seguimiento y control.docx](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-de-seguimiento-y-control-de-proyecto-entrevista-sistemhuerto/files/10158486/Rubrica.reporte.de.practica.de.seguimiento.y.control.docx)

Reporte:::::
[S4GPS 01 - Práctica Seguimiento y Control.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-de-seguimiento-y-control-de-proyecto-entrevista-sistemhuerto/files/10158487/S4GPS.01.-.Practica.Seguimiento.y.Control.pdf)

**Comment by IsaHuerta23** [comment]
Portada: 25.
Procedimiento: 25.
Figuras, ilustraciones y fotografías: 25.
Resultados y conclusiones: 25.
Total: 100. 
Calificación: 50.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
